# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a1c38d4cfabfc5f951da93560450219655b381b2ecb11c3bc39a551337b28b83be7197340b877eaafcefd32bc70d2ec236e8346f6afdfb12f6c0a128bded4ca2

test:
  secret_key_base: a9ef45b3b520800513b13aefa915a91d0bff02a62349df509dd5bd52d607562433e2351e095b757e0d3aaf769745fc08edcf5176e384cba8388d34b9c76665aa

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
